board/pluto: cleanup init scripts
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>

diff --git a/board/pluto/S10mdev b/board/pluto/S10mdev
--- a/board/pluto/S10mdev
+++ b/board/pluto/S10mdev
@@ -5,11 +5,12 @@
 
 case "$1" in
   start)
-	echo "Starting mdev..."
+	echo -n "Starting mdev: "
 	echo /sbin/mdev >/proc/sys/kernel/hotplug
 	/sbin/mdev -s
 	# coldplug modules
 	# find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	;;
   stop)
 	;;
diff --git a/board/pluto/S15watchdog b/board/pluto/S15watchdog
--- a/board/pluto/S15watchdog
+++ b/board/pluto/S15watchdog
@@ -5,8 +5,9 @@
 
 case "$1" in
  start)
-	echo "Starting watchdog..."
+	echo -n "Starting watchdog: "
 	watchdog -t 5 -T 10 /dev/watchdog
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
 	;;
   stop)
 	;;
diff --git a/board/pluto/S20urandom b/board/pluto/S20urandom
--- a/board/pluto/S20urandom
+++ b/board/pluto/S20urandom
@@ -11,17 +11,13 @@
 
 case "$1" in
 	start|"")
-		# check for read only file syste
-		if [ "$VERBOSE" != no ]
-		then
-			printf "Initializing random number generator... "
-		fi
+		echo -n "Starting initializing random number generator: "
+
 		# Load and then save 512 bytes,
 		# which is the size of the entropy pool
 
-		dmesg | grep SPI-NOR-UniqueID | cut -d " " -f 4 | sha512sum >/dev/urandom
-
-		[ "$VERBOSE" != no ] && echo "done."
+		dmesg | sha512sum > /dev/urandom
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
 		;;
 	stop)
 
diff --git a/board/pluto/S23udc b/board/pluto/S23udc
--- a/board/pluto/S23udc
+++ b/board/pluto/S23udc
@@ -17,10 +17,10 @@ create_iiod_context_attributes() {
 
 case "$1" in
   start)
- 	echo "Starting UDC Gadgets"
-	mount configfs -t configfs /sys/kernel/config >> /dev/null
+	echo -n "Starting UDC Gadgets: "
+	mount configfs -t configfs /sys/kernel/config 2> /dev/null
 
-	mkdir $GADGET
+	mkdir -p $GADGET
 
 	model=`cat /sys/firmware/devicetree/base/model | tr / -`
 
@@ -35,15 +35,15 @@ case "$1" in
 	echo 0x0456 > $GADGET/idVendor
 	echo $USBPID > $GADGET/idProduct
 
-	mkdir $GADGET/strings/0x409
+	mkdir -p $GADGET/strings/0x409
 	echo "Analog Devices Inc." > $GADGET/strings/0x409/manufacturer
 	echo $PRODUCT > $GADGET/strings/0x409/product
 	echo $serial > $GADGET/strings/0x409/serialnumber
 
-	mkdir $GADGET/functions/ffs.iio_ffs
-	mkdir $GADGET/functions/acm.usb0
-	mkdir $GADGET/functions/rndis.0
-	mkdir $GADGET/functions/mass_storage.0
+	mkdir -p $GADGET/functions/ffs.iio_ffs
+	mkdir -p $GADGET/functions/acm.usb0
+	mkdir -p $GADGET/functions/rndis.0
+	mkdir -p $GADGET/functions/mass_storage.0
 
 #	echo /opt/vfat.img > $GADGET/functions/mass_storage.0/lun.0/file
 	echo Y > $GADGET/functions/mass_storage.0/lun.0/removable
@@ -54,8 +54,8 @@ case "$1" in
 	echo $host_addr > $GADGET/functions/rndis.0/host_addr
 	echo $dev_addr > $GADGET/functions/rndis.0/dev_addr
 
-	mkdir $GADGET/configs/c.1
-	mkdir $GADGET/configs/c.1/strings/0x409
+	mkdir -p $GADGET/configs/c.1
+	mkdir -p $GADGET/configs/c.1/strings/0x409
 	echo "RNDIS/MSD/ACM/IIOUSBD" > $GADGET/configs/c.1/strings/0x409/configuration
 	echo 500 > $GADGET/configs/c.1/MaxPower
 
@@ -64,17 +64,19 @@ case "$1" in
 	ln -s $GADGET/functions/acm.usb0 $GADGET/configs/c.1
 	ln -s $GADGET/functions/ffs.iio_ffs $GADGET/configs/c.1/ffs.iio_ffs
 
-	mkdir /dev/iio_ffs
-	mount iio_ffs -t functionfs /dev/iio_ffs
+	mkdir -p /dev/iio_ffs
+	mount iio_ffs -t functionfs /dev/iio_ffs 2> /dev/null
 
 	start-stop-daemon -S -b -q -m -p /var/run/iiod.pid -x  /usr/sbin/iiod  -- $IIOD_OPTS
 	sleep 0.2
 
 	echo ci_hdrc.0 > $GADGET/UDC
 
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+
 	;;
   stop)
-	echo -n "Stopping UDC Gadgets ..."
+	echo "Stopping UDC Gadgets"
 	echo "" > $GADGET/UDC
 
 	start-stop-daemon -K -q -p /var/run/iiod.pid 2>/dev/null
@@ -93,7 +95,7 @@ case "$1" in
 	rmdir $GADGET/functions/rndis.0
 	rmdir $GADGET/functions/mass_storage.0
 
-	rmdir $GADGET
+	rmdir $GADGET 2> /dev/null
 
 	;;
   restart|reload)
diff --git a/board/pluto/S41network b/board/pluto/S41network
--- a/board/pluto/S41network
+++ b/board/pluto/S41network
@@ -5,17 +5,17 @@ source /etc/device_config
 
 case "$1" in
 	start)
-		echo "Starting dhcpd Daemon& httpd Server"
+		echo -n "Starting dhcpd Daemon & httpd Server: "
 		start-stop-daemon -S -b -q -m -p /var/run/udhcpd.pid -x /usr/sbin/udhcpd -- $UDHCPD_CONF
 		httpd -h /www
-		exit $?
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
 		;;
 
 	stop)
-		echo "Stopping dhcpd Server Daemon"
+		echo -n "Stopping dhcpd Daemon & httpd Server: "
 		killall -7 httpd
 		start-stop-daemon -K -q -p /var/run/udhcpd.pid 2>/dev/null
-		exit $?
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
 		;;
 
 	restart)
diff --git a/board/pluto/S45msd b/board/pluto/S45msd
--- a/board/pluto/S45msd
+++ b/board/pluto/S45msd
@@ -24,7 +24,7 @@ patch_html_page() {
 
 case "$1" in
 	start)
-		echo "Starting MSD Daemon"
+		echo -n "Starting MSD Daemon: "
 		patch_html_page /www/index.html /www/img/version.js
 		losetup /dev/loop7 $img -o 512
 		mount /dev/loop7 /mnt
@@ -36,13 +36,13 @@ case "$1" in
 		echo $img > $file
 
 		start-stop-daemon -S -b -q -m -p /var/run/update.pid -x /bin/sh -- /sbin/update.sh
-		exit $?
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
 		;;
 
 	stop)
-		echo "Stopping MSD Daemon"
+		echo -n "Stopping MSD Daemon: "
 		start-stop-daemon -K -q -p /var/run/update.pid 2>/dev/null
-		exit $?
+		[ $? = 0 ] && echo "OK" || echo "FAIL"
 		;;
 
 	restart)
